

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "TseHn2017Application\App.config"
//     Connection String Name: "TseActasPresidenteConnectionString"
//     Connection String:      "data source=localhost;initial catalog=TseActasPresidente;persist security info=True;user id=sa;password=**zapped**;;multipleactiveresultsets=True;App=EntityFramework"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Express Edition (64-bit)
// Database Engine Edition: Express

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace TseHn2017Application.AppCode.Context
{
    using System.Linq;

    #region Unit of work

    public interface ITseActasPresidenteDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Acta> Actas { get; set; } // Acta
        System.Data.Entity.DbSet<Voto> Votoes { get; set; } // Voto

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class TseActasPresidenteDbContext : System.Data.Entity.DbContext, ITseActasPresidenteDbContext
    {
        public System.Data.Entity.DbSet<Acta> Actas { get; set; } // Acta
        public System.Data.Entity.DbSet<Voto> Votoes { get; set; } // Voto

        static TseActasPresidenteDbContext()
        {
            System.Data.Entity.Database.SetInitializer<TseActasPresidenteDbContext>(null);
        }

        public TseActasPresidenteDbContext()
            : base("Name=TseActasPresidenteConnectionString")
        {
        }

        public TseActasPresidenteDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public TseActasPresidenteDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public TseActasPresidenteDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public TseActasPresidenteDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new ActaConfiguration());
            modelBuilder.Configurations.Add(new VotoConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new ActaConfiguration(schema));
            modelBuilder.Configurations.Add(new VotoConfiguration(schema));
            return modelBuilder;
        }
    }
    #endregion

    #region Database context factory

    public class TseActasPresidenteDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<TseActasPresidenteDbContext>
    {
        public TseActasPresidenteDbContext Create()
        {
            return new TseActasPresidenteDbContext();
        }
    }

    #endregion

    #region Fake Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class FakeTseActasPresidenteDbContext : ITseActasPresidenteDbContext
    {
        public System.Data.Entity.DbSet<Acta> Actas { get; set; }
        public System.Data.Entity.DbSet<Voto> Votoes { get; set; }

        public FakeTseActasPresidenteDbContext()
        {
            Actas = new FakeDbSet<Acta>("CodActa");
            Votoes = new FakeDbSet<Voto>("IdVoto");
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
        public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
        private System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
        public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
        private System.Data.Entity.Database _database;
        public System.Data.Entity.Database Database { get { return _database; } }
        public System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity)
        {
            throw new System.NotImplementedException();
        }
        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors()
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet Set(System.Type entityType)
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public override string ToString()
        {
            throw new System.NotImplementedException();
        }

    }

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class FakeDbSet<TEntity> : System.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity> where TEntity : class
    {
        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
        private readonly IQueryable _query;

        public FakeDbSet()
        {
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new System.ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new System.ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(System.Threading.CancellationToken cancellationToken, params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken);
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues));
        }

        public override System.Collections.Generic.IEnumerable<TEntity> AddRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Add(entity);
            }
            return items;
        }

        public override TEntity Add(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override System.Collections.Generic.IEnumerable<TEntity> RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Remove(entity);
            }
            return items;
        }

        public override TEntity Remove(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Remove(item);
            return item;
        }

        public override TEntity Attach(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override TEntity Create()
        {
            return System.Activator.CreateInstance<TEntity>();
        }

        public override TDerivedEntity Create<TDerivedEntity>()
        {
            return System.Activator.CreateInstance<TDerivedEntity>();
        }

        public override System.Collections.ObjectModel.ObservableCollection<TEntity> Local
        {
            get { return _data; }
        }

        System.Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        System.Linq.Expressions.Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); }
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator<TEntity> System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class FakeDbAsyncQueryProvider<TEntity> : System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
    {
        private readonly IQueryProvider _inner;

        public FakeDbAsyncQueryProvider(IQueryProvider inner)
        {
            _inner = inner;
        }

        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TEntity>(expression);
        }

        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TElement>(expression);
        }

        public object Execute(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute(expression);
        }

        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute<TResult>(expression);
        }

        public System.Threading.Tasks.Task<object> ExecuteAsync(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute(expression));
        }

        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression));
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable)
            : base(enumerable)
        { }

        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression)
            : base(expression)
        { }

        public System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T> GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator System.Data.Entity.Infrastructure.IDbAsyncEnumerable.GetAsyncEnumerator()
        {
            return GetAsyncEnumerator();
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<T>(this); }
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class FakeDbAsyncEnumerator<T> : System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T>
    {
        private readonly System.Collections.Generic.IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public void Dispose()
        {
            _inner.Dispose();
        }

        public System.Threading.Tasks.Task<bool> MoveNextAsync(System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext());
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        object System.Data.Entity.Infrastructure.IDbAsyncEnumerator.Current
        {
            get { return Current; }
        }
    }

    #endregion

    #region POCO classes

    // Acta
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Acta
    {
        public int CodActa { get; set; } // CodActa (Primary key)
        public int NumNivel { get; set; } // NumNivel
        public string NomNivel { get; set; } // NomNivel (length: 500)
        public int CodMer { get; set; } // CodMER
        public int CodDepartamento { get; set; } // CodDepartamento
        public int CodMunicipio { get; set; } // CodMunicipio
        public string NomDepartamento { get; set; } // NomDepartamento (length: 500)
        public string NomMunicipio { get; set; } // NomMunicipio (length: 500)
        public int CodCentroVotacion { get; set; } // CodCentroVotacion
        public string NomCentroVotacion { get; set; } // NomCentroVotacion (length: 500)
        public int CodEstado { get; set; } // CodEstado
        public string NomEstado { get; set; } // NomEstado (length: 500)
        public int NumVotosValidos { get; set; } // NumVotosValidos
        public int NumVotosBlancos { get; set; } // NumVotosBlancos
        public int NumVotosNulos { get; set; } // NumVotosNulos
        public int NumVotosTotal { get; set; } // NumVotosTotal
        public int NumPapeletasRecibidas { get; set; } // NumPapeletasRecibidas
        public int NumPapeletasSobrantes { get; set; } // NumPapeletasSobrantes
        public int NumPapeletasUtilizadas { get; set; } // NumPapeletasUtilizadas
        public string CodBarra { get; set; } // CodBarra (length: 500)
        public string Url { get; set; } // Url (length: 500)
    }

    // Voto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Voto
    {
        public int CodCandidato { get; set; } // CodCandidato
        public string NomCandidato { get; set; } // NomCandidato (length: 500)
        public string IdentidadCandidato { get; set; } // IdentidadCandidato (length: 500)
        public int CodPartido { get; set; } // CodPartido
        public string NomPartido { get; set; } // NomPartido (length: 500)
        public int NumVotos { get; set; } // NumVotos
        public int NumPosicion { get; set; } // NumPosicion
        public int? CodActa { get; set; } // CodActa
        public decimal IdVoto { get; set; } // IdVoto (Primary key)
    }

    #endregion

    #region POCO Configuration

    // Acta
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ActaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Acta>
    {
        public ActaConfiguration()
            : this("dbo")
        {
        }

        public ActaConfiguration(string schema)
        {
            ToTable("Acta", schema);
            HasKey(x => x.CodActa);

            Property(x => x.CodActa).HasColumnName(@"CodActa").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NumNivel).HasColumnName(@"NumNivel").HasColumnType("int").IsRequired();
            Property(x => x.NomNivel).HasColumnName(@"NomNivel").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.CodMer).HasColumnName(@"CodMER").HasColumnType("int").IsRequired();
            Property(x => x.CodDepartamento).HasColumnName(@"CodDepartamento").HasColumnType("int").IsRequired();
            Property(x => x.CodMunicipio).HasColumnName(@"CodMunicipio").HasColumnType("int").IsRequired();
            Property(x => x.NomDepartamento).HasColumnName(@"NomDepartamento").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.NomMunicipio).HasColumnName(@"NomMunicipio").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.CodCentroVotacion).HasColumnName(@"CodCentroVotacion").HasColumnType("int").IsRequired();
            Property(x => x.NomCentroVotacion).HasColumnName(@"NomCentroVotacion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.CodEstado).HasColumnName(@"CodEstado").HasColumnType("int").IsRequired();
            Property(x => x.NomEstado).HasColumnName(@"NomEstado").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.NumVotosValidos).HasColumnName(@"NumVotosValidos").HasColumnType("int").IsRequired();
            Property(x => x.NumVotosBlancos).HasColumnName(@"NumVotosBlancos").HasColumnType("int").IsRequired();
            Property(x => x.NumVotosNulos).HasColumnName(@"NumVotosNulos").HasColumnType("int").IsRequired();
            Property(x => x.NumVotosTotal).HasColumnName(@"NumVotosTotal").HasColumnType("int").IsRequired();
            Property(x => x.NumPapeletasRecibidas).HasColumnName(@"NumPapeletasRecibidas").HasColumnType("int").IsRequired();
            Property(x => x.NumPapeletasSobrantes).HasColumnName(@"NumPapeletasSobrantes").HasColumnType("int").IsRequired();
            Property(x => x.NumPapeletasUtilizadas).HasColumnName(@"NumPapeletasUtilizadas").HasColumnType("int").IsRequired();
            Property(x => x.CodBarra).HasColumnName(@"CodBarra").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Url).HasColumnName(@"Url").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
        }
    }

    // Voto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class VotoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Voto>
    {
        public VotoConfiguration()
            : this("dbo")
        {
        }

        public VotoConfiguration(string schema)
        {
            ToTable("Voto", schema);
            HasKey(x => x.IdVoto);

            Property(x => x.CodCandidato).HasColumnName(@"CodCandidato").HasColumnType("int").IsRequired();
            Property(x => x.NomCandidato).HasColumnName(@"NomCandidato").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.IdentidadCandidato).HasColumnName(@"IdentidadCandidato").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.CodPartido).HasColumnName(@"CodPartido").HasColumnType("int").IsRequired();
            Property(x => x.NomPartido).HasColumnName(@"NomPartido").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.NumVotos).HasColumnName(@"NumVotos").HasColumnType("int").IsRequired();
            Property(x => x.NumPosicion).HasColumnName(@"NumPosicion").HasColumnType("int").IsRequired();
            Property(x => x.CodActa).HasColumnName(@"CodActa").HasColumnType("int").IsOptional();
            Property(x => x.IdVoto).HasColumnName(@"IdVoto").HasColumnType("numeric").IsRequired().HasPrecision(18,0).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
        }
    }

    #endregion

}
// </auto-generated>

